#!/usr/bin/env fish
set -Ux SEMANTIC_DESKTOP_AGRAPH_HOST "localhost"
set -Ux SEMANTIC_DESKTOP_AGRAPH_PORT "10035"
set -Ux SEMANTIC_DESKTOP_AGRAPH_REPO "repo"
set -Ux SEMANTIC_DESKTOP_AGRAPH_USER "super"
set -Ux SEMANTIC_DESKTOP_AGRAPH_PASS "super"
